// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDKBcHqFuqjN9-E_rdoif3cGwoup-oZk',
    appId: '1:941287839428:web:4ab7fdf626b1487edd1b91',
    messagingSenderId: '941287839428',
    projectId: 'eldepizza',
    authDomain: 'eldepizza.firebaseapp.com',
    storageBucket: 'eldepizza.appspot.com',
    measurementId: 'G-367KDVND2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8TTc3cxCmrTLzVNcWpQkVMd7StNUk94c',
    appId: '1:941287839428:android:033a53390657656fdd1b91',
    messagingSenderId: '941287839428',
    projectId: 'eldepizza',
    storageBucket: 'eldepizza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzcP1VsL9HFRz31QKFbOu7T4rxoOP8_Cs',
    appId: '1:941287839428:ios:558469deeffa6ef7dd1b91',
    messagingSenderId: '941287839428',
    projectId: 'eldepizza',
    storageBucket: 'eldepizza.appspot.com',
    iosClientId: '941287839428-s88sq3iscioc1j4es31faqbe9alntnpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldepizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzcP1VsL9HFRz31QKFbOu7T4rxoOP8_Cs',
    appId: '1:941287839428:ios:558469deeffa6ef7dd1b91',
    messagingSenderId: '941287839428',
    projectId: 'eldepizza',
    storageBucket: 'eldepizza.appspot.com',
    iosClientId: '941287839428-s88sq3iscioc1j4es31faqbe9alntnpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldepizza',
  );
}
